apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-api-key
  namespace: demo
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dev-api-credentials
  data:
  - secretKey: api-key
    remoteRef:
      key: "dev"
      property: "api-key"